Repository CS2113-AY1819S2-T08-3/main, pull requests merged in 2019-04, with the labels that each got.

#137 Update Dev Guide introduction
  docs/DeveloperGuide.adoc
Labels: priority.High

#138 Update view command implementation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/planmysem/common/Messages.java
  src/planmysem/logic/commands/ViewCommand.java
  src/planmysem/logic/parser/ViewCommandParser.java
Labels: priority.High

#139 Update view command to fix minor bug
  src/planmysem/logic/commands/ViewCommand.java
  src/planmysem/logic/parser/ViewCommandParser.java
  src/planmysem/model/semester/Semester.java
  test/java/planmysem/model/PlannerTest.java
Labels: priority.High

#143 Add JUnit Tests
  src/planmysem/common/Messages.java
  src/planmysem/common/Utils.java
  src/planmysem/logic/commands/FindCommand.java
  src/planmysem/logic/commands/ListCommand.java
  test/java/planmysem/logic/Commands/FindCommandTest.java
  test/java/planmysem/logic/Commands/ListCommandTest.java
Labels: priority.High

#144 Update Test Cases to raise coverage
  src/planmysem/logic/commands/FindCommand.java
  test/java/planmysem/logic/Commands/FindCommandTest.java
  test/java/planmysem/logic/Commands/UndoCommandTest.java
Labels: priority.High

#145 Add JUnit tests for ViewCommandParser and ViewCommand
  src/planmysem/logic/commands/ViewCommand.java
  src/planmysem/logic/parser/ViewCommandParser.java
  test/java/planmysem/logic/Commands/ViewCommandTest.java
  test/java/planmysem/logic/parser/AddCommandParserTest.java
  test/java/planmysem/logic/parser/ViewCommandParserTest.java
Labels: priority.High

#147 ParserManagerTest: Update JUnit test for view command
  test/java/planmysem/logic/parser/ParserManagerTest.java
Labels: priority.High

#148 ViewCommand: Update view week feature to resize week view
  src/planmysem/logic/commands/ViewCommand.java
Labels: priority.Medium

#150 Fix bug in semester initialization and update JUnit tests
  src/planmysem/logic/commands/ViewCommand.java
  src/planmysem/model/semester/Semester.java
  test/java/planmysem/logic/Commands/ViewCommandTest.java
  test/java/planmysem/model/Semester/SemesterTest.java
Labels: priority.High

#152 Add PPP of marcus-pzj
  docs/UserGuide.adoc
  docs/team/marcus-pzj.adoc
  src/planmysem/common/Messages.java
  test/java/planmysem/logic/Commands/FindCommandTest.java
Labels: priority.High

#153 Add PPP (Julian)
  docs/UserGuide.adoc
  docs/team/macchazuki.adoc
  src/planmysem/storage/Encryptor.java
  src/planmysem/storage/KeyStorage.java
  src/planmysem/storage/StorageFile.java
  test/java/planmysem/logic/Commands/ExportCommandTest.java
Labels: priority.High

#154 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Sem1.PNG
  docs/images/Sem2.PNG
  docs/team/dingheng4448.adoc
Labels: priority.High

#155 Update seanieyap.adoc
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/seanieyap.adoc
  src/planmysem/common/Messages.java
  src/planmysem/logic/commands/DeleteCommand.java
  src/planmysem/logic/commands/FindCommand.java
  src/planmysem/logic/commands/ListCommand.java
  test/java/planmysem/logic/Commands/FindCommandTest.java
Labels: priority.High

#156 Rename image extension
  docs/images/Sem1.png
  docs/images/Sem2.png
Labels: priority.High

#157 Update seanieyap.adoc and documentation examples
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Add_Command_Output_1.png
  docs/images/Delete_Command_Output.png
  docs/images/Delete_Command_Output_!.png
  docs/images/Edit_Command_Output_1.png
  docs/images/List_Command_Output_1.png
  docs/team/seanieyap.adoc
  src/planmysem/common/Messages.java
  src/planmysem/logic/commands/FindCommand.java
Labels: priority.High

#180 Add parser tests to import/export and exceptions
  docs/DeveloperGuide.adoc
  docs/team/macchazuki.adoc
  src/planmysem/logic/commands/ExportCommand.java
  src/planmysem/logic/commands/ImportCommand.java
  src/planmysem/logic/parser/ExportCommandParser.java
  src/planmysem/logic/parser/ImportCommandParser.java
  src/planmysem/logic/parser/Parser.java
  src/planmysem/logic/parser/ParserManager.java
  src/planmysem/model/semester/IcsSemester.java
  src/planmysem/storage/Encryptor.java
  test/java/planmysem/logic/Commands/ExportCommandTest.java
  test/java/planmysem/logic/parser/ExportCommandParserTest.java
  test/java/planmysem/logic/parser/ImportCommandParserTest.java
  test/java/planmysem/logic/parser/ParserManagerTest.java
  test/java/planmysem/storage/EncryptorTest.java
Labels: type.Enhancement, type.Task

#181 v1.3.1
  docs/team/seanieyap.adoc
  src/planmysem/logic/commands/FindCommand.java
Labels: priority.High

#184 Fixed ExportCommandTest bugs
  test/java/planmysem/logic/Commands/ExportCommandTest.java
  test/java/planmysem/logic/Commands/ImportCommandTest.java
  test/model/ImportTest/ImportTest.ics
  test/model/ImportTest/ImportTest2.ics
Labels: priority.High

#185 Update DeveloperGuide.adoc with tips from TA
  docs/DeveloperGuide.adoc
  docs/Diagrams.pptx
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/LogicClassDiagram.uml
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/ModelClassDiagram.uml
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageClassDiagram.uml
  docs/diagrams/UiClassDiagram.uml
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/Architecture.png
  docs/images/ArchitectureDiagram.png
  docs/images/LogicComponentClassDiagram.png
  docs/images/ModelComponentClassDiagram.png
  docs/images/UiComponentClassDiagram.png
  docs/stylesheets/asciidoctor.css
  src/planmysem/Main.java
  src/planmysem/model/Planner.java
  src/planmysem/ui/UiManager.java
Labels: priority.Medium

#186 Update tests exportcommand and keystorage
  src/planmysem/storage/KeyStorage.java
  test/java/planmysem/logic/Commands/ExportCommandTest.java
  test/java/planmysem/storage/EncryptorTest.java
  test/java/planmysem/storage/KeyStorageTest.java
Labels: priority.High

#187 Edit ListCommandParser for "list all"
  src/planmysem/common/Utils.java
  src/planmysem/logic/commands/ListCommand.java
  src/planmysem/logic/parser/ListCommandParser.java
  src/planmysem/logic/parser/Parser.java
  test/java/planmysem/logic/CommandHistoryTest.java
  test/java/planmysem/logic/Commands/FindCommandTest.java
  test/java/planmysem/logic/Commands/HistoryCommandTest.java
  test/java/planmysem/logic/Commands/ListCommandTest.java
  test/java/planmysem/logic/Commands/RedoCommandTest.java
  test/java/planmysem/logic/Commands/UndoCommandTest.java
  test/java/planmysem/testutil/SlotBuilder.java
Labels: priority.High

#188 Update seanieyap.adoc with v1.4 updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/seanieyap.adoc
Labels: priority.Medium

#190 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/planmysem/logic/commands/ViewCommand.java
Labels: priority.High

#191 Update Documentation
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Find_Command_Output_1.png
  docs/team/marcus-pzj.adoc
  src/planmysem/common/Messages.java
  src/planmysem/logic/commands/ClearCommand.java
  src/planmysem/logic/commands/FindCommand.java
  test/java/planmysem/logic/Commands/ClearCommandTest.java
  test/java/planmysem/logic/Commands/FindCommandTest.java
  test/java/planmysem/logic/Commands/RedoCommandTest.java
  test/java/planmysem/logic/Commands/UndoCommandTest.java
Labels: priority.Medium

#192 Updates to documentation
  docs/DeveloperGuide.adoc
  docs/diagrams/FindSequenceDiagram.pptx
  docs/images/FindSequenceDiagram.png
  docs/images/Find_Command_Output.png
  docs/team/marcus-pzj.adoc
Labels: priority.Medium

#193 Update documentation
  docs/DeveloperGuide.adoc
  docs/diagrams/ViewMonthSequenceDiagram.pptx
  docs/images/Ui.png
  docs/images/ViewMonthSequenceDiagram.png
  docs/team/dingheng4448.adoc
  src/planmysem/logic/commands/ViewCommand.java
Labels: priority.High

#194 Update PPP
  docs/team/marcus-pzj.adoc
Labels: priority.Medium

#195 Add images
  docs/diagrams/FindListHistoryActivityDiagram.pptx
  docs/images/FindListHistoryActivityDiagram.png
Labels: priority.Medium

#196 DeveloperGuide: Update view month sequence diagram
  docs/diagrams/ViewMonthSequenceDiagram.pptx
  docs/images/ViewMonthSequenceDiagram.png
Labels: priority.High

#197 Update documentation
  docs/DeveloperGuide.adoc
  docs/diagrams/FindCommunicationDiagram.pptx
  docs/diagrams/FindListHistoryActivityDiagram.pptx
  docs/diagrams/FindSequenceDiagram.pptx
  docs/images/FindCommunicationDiagram.png
  docs/images/FindListHistoryActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/team/marcus-pzj.adoc
Labels: priority.Medium

#199 Update documentation and keystorage tests
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ExportActivityDiagram.pptx
  docs/diagrams/ExportSequenceDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/images/ExportCommandActivityDiagram.PNG
  docs/images/ExportCommandSequenceDiagram.PNG
  docs/team/macchazuki.adoc
  docs/team/seanieyap.adoc
  src/planmysem/logic/commands/ExportCommand.java
  src/planmysem/model/semester/IcsSemester.java
  src/planmysem/storage/Encryptor.java
  src/planmysem/storage/KeyStorage.java
  src/planmysem/storage/StorageFile.java
  test/java/planmysem/logic/Commands/ExportCommandTest.java
  test/java/planmysem/storage/EncryptorTest.java
  test/java/planmysem/storage/KeyStorageTest.java
Labels: priority.High

#198 Fix broken links
  docs/DeveloperGuide.adoc
  docs/team/marcus-pzj.adoc
  src/planmysem/common/Messages.java
  src/planmysem/logic/commands/ListCommand.java
  src/planmysem/logic/parser/ListCommandParser.java
  test/java/planmysem/logic/Commands/ListCommandTest.java
Labels: priority.Medium

#200 Fix bug in listing and editing slots
  src/planmysem/common/Messages.java
  src/planmysem/logic/commands/ListCommand.java
  test/java/planmysem/logic/Commands/ListCommandTest.java
Labels: priority.High, severity.High, type.Bug

#201 Update PPP
  docs/team/macchazuki.adoc
Labels: priority.High

#202 Fixed wrong link in PPP
  docs/team/macchazuki.adoc
Labels: priority.High

#203 Semester: Enhance code quality
  src/planmysem/logic/commands/ViewCommand.java
  src/planmysem/model/semester/Semester.java
Labels: priority.High

#204 Update DeveloperGuide
  docs/DeveloperGuide.adoc
  src/planmysem/logic/commands/ViewCommand.java
  src/planmysem/model/semester/Semester.java
Labels: priority.High

#206 Update documentation
  docs/team/macchazuki.adoc
Labels: priority.High

#205 v1.4
  docs/DeveloperGuide.adoc
  src/planmysem/Main.java
Labels: priority.High
