Repository CS2113-AY1819S2-T08-3/main, pull requests merged in 2019-03, with the labels that each got.

#45 Update documents to adhere to guidelines
  docs/AboutUs.adoc
  docs/images/Ui.png
  docs/images/dingheng4448.png
  docs/images/julianlim.jpg
  docs/images/limdingheng.jpg
  docs/images/macchazuki.png
  docs/images/marcus-pzj.png
  docs/images/marcusphua.jpeg
  docs/images/seanieyap.png
  docs/images/seanyap.jpg
  docs/team/dingheng4448.adoc
  docs/team/macchazuki.adoc
  docs/team/marcus-pzj.adoc
  docs/team/seanieyap.adoc
Labels: priority.High

#51 v1.1
  PlanMySem.txt
  src/planmysem/commands/AddCommandP.java
  src/planmysem/commands/CommandP.java
  src/planmysem/commands/HistoryCommand.java
  src/planmysem/data/Planner.java
  src/planmysem/data/semester/Day.java
  src/planmysem/parser/ParserP.java
  src/planmysem/storage/jaxb/AdaptedDay.java
  src/planmysem/storage/jaxb/AdaptedPlanner.java
  src/planmysem/storage/jaxb/AdaptedSemester.java
  src/planmysem/ui/MainWindowP.java
Labels: priority.High

#54 Initialize weekType for each Day
  src/planmysem/data/Planner.java
  src/planmysem/data/semester/Day.java
Labels: priority.Medium

#55 Update code to initialize planner
  AcademicCalendar.txt
  src/planmysem/data/Planner.java
  src/planmysem/data/semester/Day.java
Labels: priority.High

#61 Enhance add functionality
  docs/UserGuide.adoc
  src/planmysem/commands/AddCommandP.java
  src/planmysem/commands/EditCommandP.java
  src/planmysem/common/Utils.java
  src/planmysem/data/recurrence/Recurrence.java
  src/planmysem/data/semester/Semester.java
  src/planmysem/parser/ParserP.java
  src/planmysem/storage/jaxb/AdaptedDay.java
  src/planmysem/storage/jaxb/AdaptedSemester.java
Labels: type.Enhancement

#76 Add JUnit test for Planner
  src/planmysem/data/Planner.java
  test/java/planmysem/data/PlannerTest.java
Labels: priority.High, type.Task

#79 Enhance ListCommandP
  PlanMySem.txt
  src/planmysem/commands/FindCommandP.java
  src/planmysem/commands/ListCommandP.java
  src/planmysem/parser/ParserP.java
Labels: priority.High

#81 Update documentation for view command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, type.Task

#82 Refactor class names, remove remaining traces of addressbook
  src/planmysem/Main.java
  src/planmysem/commands/AddCommand.java
  src/planmysem/commands/AddCommandP.java
  src/planmysem/commands/ClearCommand.java
  src/planmysem/commands/ClearCommandP.java
  src/planmysem/commands/Command.java
  src/planmysem/commands/CommandP.java
  src/planmysem/commands/CommandResult.java
  src/planmysem/commands/CommandResultP.java
  src/planmysem/commands/DeleteCommand.java
  src/planmysem/commands/DeleteCommandP.java
  src/planmysem/commands/EditCommand.java
  src/planmysem/commands/ExitCommand.java
  src/planmysem/commands/ExitCommandP.java
  src/planmysem/commands/ExportCommand.java
  src/planmysem/commands/FindCommand.java
  src/planmysem/commands/FindCommandP.java
  src/planmysem/commands/HelpCommand.java
  src/planmysem/commands/HelpCommandP.java
  src/planmysem/commands/HistoryCommand.java
  src/planmysem/commands/IncorrectCommand.java
  src/planmysem/commands/IncorrectCommandP.java
  src/planmysem/commands/ListCommand.java
  src/planmysem/commands/ListCommandP.java
  src/planmysem/commands/ViewAllCommand.java
  src/planmysem/commands/ViewCommand.java
  src/planmysem/data/AddressBook.java
  src/planmysem/data/person/Address.java
  src/planmysem/data/person/Email.java
  src/planmysem/data/person/Name.java
  src/planmysem/data/person/Person.java
  src/planmysem/data/person/Phone.java
  src/planmysem/data/person/ReadOnlyPerson.java
  src/planmysem/data/person/UniquePersonList.java
  src/planmysem/data/slot/Slot.java
  src/planmysem/logic/Logic.java
  src/planmysem/logic/LogicP.java
  src/planmysem/parser/Parser.java
  src/planmysem/parser/ParserP.java
  src/planmysem/storage/StorageFile.java
  src/planmysem/storage/StorageFileP.java
  src/planmysem/storage/jaxb/AdaptedAddressBook.java
  src/planmysem/storage/jaxb/AdaptedPerson.java
  src/planmysem/storage/jaxb/AdaptedSlot.java
  src/planmysem/storage/jaxb/AdaptedTag.java
  src/planmysem/storage/jaxb/AdaptedTagP.java
  src/planmysem/ui/Formatter.java
  src/planmysem/ui/Gui.java
  src/planmysem/ui/MainWindow.java
  src/planmysem/ui/MainWindowP.java
  src/planmysem/ui/mainwindow.fxml
  src/planmysem/ui/mainwindowP.fxml
  test/java/planmysem/logic/LogicTest.java
  test/java/planmysem/parser/ParserTest.java
  test/java/planmysem/storage/StorageFileTest.java
Labels: priority.High

#83 Add User Stories; Fulfil 30 user stories
  docs/DeveloperGuide.adoc
Labels: priority.Medium, type.Task

#85 Resolve checkstyle errors
  src/planmysem/parser/Parser.java
Labels: priority.High

#86 Enhance FindCommand
  docs/DeveloperGuide.adoc
  src/planmysem/commands/FindCommand.java
  src/planmysem/commands/ListCommand.java
  src/planmysem/parser/Parser.java
Labels: priority.High

#87 Add view command for monthly calendar view
  src/planmysem/commands/ViewCommand.java
  src/planmysem/parser/Parser.java
  src/planmysem/ui/DarkTheme.css
Labels: priority.High

#88 Add test cases for add function, Utils and other code enhancements
  PlanMySem.txt
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/planmysem/Main.java
  src/planmysem/commands/AddCommand.java
  src/planmysem/commands/DeleteCommand.java
  src/planmysem/commands/EditCommand.java
  src/planmysem/commands/FindCommand.java
  src/planmysem/common/Messages.java
  src/planmysem/common/Utils.java
  src/planmysem/data/Planner.java
  src/planmysem/data/semester/Day.java
  src/planmysem/data/semester/ReadOnlyDay.java
  src/planmysem/data/semester/Semester.java
  src/planmysem/data/slot/Location.java
  src/planmysem/data/slot/ReadOnlySlot.java
  src/planmysem/data/slot/Slot.java
  src/planmysem/data/tag/Tag.java
  src/planmysem/data/tag/TagP.java
  src/planmysem/logic/Logic.java
  src/planmysem/parser/Parser.java
  src/planmysem/storage/jaxb/AdaptedSemester.java
  src/planmysem/storage/jaxb/AdaptedSlot.java
  src/planmysem/storage/jaxb/AdaptedTag.java
  src/planmysem/ui/MainWindow.java
  test/data/StorageFileTest/InvalidData.txt
  test/data/StorageFileTest/ValidData.txt
  test/java/planmysem/common/UtilsTest.java
  test/java/planmysem/logic/LogicTest.java
  test/java/planmysem/parser/ParserTest.java
  test/java/planmysem/storage/StorageFileTest.java
Labels: priority.High

#90 Update use cases in developer guide
  docs/DeveloperGuide.adoc
Labels: priority.Medium, type.Task

#89 Update Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/planmysem/commands/FindCommand.java
  src/planmysem/commands/ListCommand.java
Labels: priority.Medium

#94 v1.2
  AcademicCalendar.txt
  README.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
  docs/images/Ui.png
  src/planmysem/common/Utils.java
  test/java/planmysem/common/UtilsTest.java
Labels: priority.High

#95 Update Ui.png, fix issues not detected in previous PR due to AppVeyor and Codacy Service Downtime
  README.adoc
  docs/images/Ui.png
  src/planmysem/common/Utils.java
  test/java/planmysem/common/UtilsTest.java
Labels: priority.High

#97 Fix Bug in FindCommand
  src/planmysem/commands/FindCommand.java
  src/planmysem/parser/Parser.java
Labels: priority.High, type.Bug

#99 Update User Guide documentation
  docs/UserGuide.adoc
Labels: priority.Medium

#100 Update UserGuide.adoc
  docs/UserGuide.adoc
  src/planmysem/commands/AddCommand.java
  src/planmysem/commands/Command.java
  src/planmysem/commands/DeleteCommand.java
  src/planmysem/commands/EditCommand.java
  src/planmysem/commands/FindCommand.java
  src/planmysem/common/Messages.java
  src/planmysem/data/semester/Semester.java
  src/planmysem/data/slot/ReadOnlySlot.java
  test/java/planmysem/logic/LogicTest.java
Labels: priority.Medium

#102 Add config file for Reposense
  .gitignore
  config.json
Labels: priority.High

#104 Edit config file in reposense
  _reposense/config.json
Labels: priority.High

#106 Update User Guide
  docs/UserGuide.adoc
  src/planmysem/ui/DarkTheme.css
Labels: priority.High

#110 Update README.adoc and UserGuide.adoc: change table layouts
  README.adoc
  docs/UserGuide.adoc
  src/planmysem/commands/EditCommand.java
  src/planmysem/commands/FindCommand.java
  src/planmysem/data/Planner.java
  src/planmysem/data/semester/Semester.java
Labels: priority.High

#108 Update User Guide
  docs/UserGuide.adoc
Labels: priority.High

#111 Enhance list and find functionality to include tags
  src/planmysem/commands/FindCommand.java
  src/planmysem/commands/ListCommand.java
  src/planmysem/common/Messages.java
  src/planmysem/parser/Parser.java
  test/java/planmysem/logic/LogicTest.java
Labels: priority.High

#114 Update User Guide and Dev Guide for encryption
  docs/DeveloperGuide.adoc
Labels: priority.High

#115 Add tests for Add, Edit and Delete commands and optimise code
  src/planmysem/commands/AddCommand.java
  src/planmysem/commands/Command.java
  src/planmysem/commands/CommandResult.java
  src/planmysem/commands/DeleteCommand.java
  src/planmysem/commands/EditCommand.java
  src/planmysem/commands/FindCommand.java
  src/planmysem/commands/ListCommand.java
  src/planmysem/common/Messages.java
  src/planmysem/common/Utils.java
  src/planmysem/data/Planner.java
  src/planmysem/data/recurrence/Recurrence.java
  src/planmysem/data/semester/Semester.java
  src/planmysem/logic/Logic.java
  src/planmysem/parser/Parser.java
  src/planmysem/ui/Formatter.java
  src/planmysem/ui/MainWindow.java
  test/java/planmysem/common/UtilsTest.java
  test/java/planmysem/data/PlannerTest.java
  test/java/planmysem/logic/LogicTest.java
Labels: priority.High

#116 Move Semester generation code
  docs/DeveloperGuide.adoc
  src/planmysem/data/Planner.java
  src/planmysem/data/semester/Semester.java
  test/java/planmysem/data/PlannerTest.java
  test/java/planmysem/logic/LogicTest.java
Labels: priority.High

#117 Update Dev Guide for initialization of Semester
  docs/DeveloperGuide.adoc
Labels: priority.High

#119 Update UserGuide.adoc with "Managing Slots" and diagrams
  docs/DeveloperGuide.adoc
  docs/HelpWindow.adoc
  docs/UsingAppVeyor.adoc
  docs/UsingCheckstyle.adoc
  docs/UsingCoveralls.adoc
  docs/UsingGradle.adoc
  docs/UsingNetlify.adoc
  docs/UsingTravis.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/DataClassDiagram.pptx
  docs/diagrams/DataClassDiagram.uml
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicClassDiagram.uml
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageClassDiagram.uml
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/Architecture.png
  docs/images/DataClassDiagram.png
  docs/images/DataClassDiagram02.png
  docs/images/LogicClassDiagram.png
  docs/images/SDforDeleteSlot.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/appveyor/add-project-1.png
  docs/images/appveyor/add-project-2.png
  docs/images/appveyor/add-project-3.png
  docs/images/appveyor/ci-log.png
  docs/images/appveyor/ci-pending.png
  docs/images/appveyor/login.png
  docs/images/appveyor/project-settings-1.png
  docs/images/appveyor/project-settings-2.png
  docs/images/appveyor/project-settings-3.png
  docs/images/checkstyle-idea-configuration.png
  docs/images/checkstyle-idea-scan-scope.png
  docs/images/chrome_save_as_pdf.png
  docs/images/coveralls/badge_repo.png
  docs/images/coveralls/coverage_asciidoc_code.png
  docs/images/coveralls/coverage_report.png
  docs/images/coveralls/disable_comments.png
  docs/images/coveralls/flick_repository_switch.png
  docs/images/coveralls/github_settings.png
  docs/images/coveralls/sync_repos.png
  docs/images/netlify/change_site_name.png
  docs/images/netlify/grant_or_request_access.png
  docs/images/netlify/netlify_details.png
  docs/images/netlify/temp_site_name.png
  src/planmysem/commands/Command.java
  src/planmysem/data/semester/Semester.java
  test/java/planmysem/parser/ParserTest.java
Labels: priority.Medium

#120 Edit Data Classes, remove unnecessary dependencies
  src/planmysem/commands/AddCommand.java
  src/planmysem/commands/DeleteCommand.java
  src/planmysem/commands/EditCommand.java
  src/planmysem/commands/FindCommand.java
  src/planmysem/commands/ListCommand.java
  src/planmysem/common/Messages.java
  src/planmysem/common/Utils.java
  src/planmysem/data/Planner.java
  src/planmysem/data/exception/DuplicateDataException.java
  src/planmysem/data/semester/Day.java
  src/planmysem/data/semester/Semester.java
  src/planmysem/data/slot/Description.java
  src/planmysem/data/slot/Location.java
  src/planmysem/data/slot/Name.java
  src/planmysem/data/slot/ReadOnlySlot.java
  src/planmysem/data/slot/Slot.java
  src/planmysem/data/tag/Tag.java
  src/planmysem/parser/Parser.java
  src/planmysem/storage/jaxb/AdaptedDay.java
  src/planmysem/storage/jaxb/AdaptedPlanner.java
  src/planmysem/storage/jaxb/AdaptedSemester.java
  src/planmysem/storage/jaxb/AdaptedSlot.java
  src/planmysem/storage/jaxb/AdaptedTag.java
  test/java/planmysem/common/UtilsTest.java
  test/java/planmysem/logic/LogicTest.java
Labels: priority.High

#124 Update view command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/planmysem/logic/commands/HelpCommand.java
  src/planmysem/logic/commands/ViewCommand.java
  src/planmysem/logic/parser/ViewCommandParser.java
  src/planmysem/model/semester/ReadOnlySemester.java
  src/planmysem/model/semester/Semester.java
Labels: priority.High

#126 Enhance FindCommand to use Levenshtein Distance
  src/planmysem/common/Messages.java
  src/planmysem/common/Utils.java
  src/planmysem/logic/commands/FindCommand.java
  src/planmysem/logic/commands/ListCommand.java
  src/planmysem/model/semester/WeightedName.java
Labels: priority.High

#127 Update diagrams and minor text in DeveloperGuide and AboutUs
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  docs/team/seanieyap.adoc
  src/planmysem/common/Messages.java
  src/planmysem/logic/Logic.java
  src/planmysem/logic/LogicManager.java
  src/planmysem/logic/commands/FindCommand.java
  src/planmysem/logic/commands/ListCommand.java
  src/planmysem/logic/commands/RedoCommand.java
  src/planmysem/logic/commands/UndoCommand.java
  src/planmysem/model/Model.java
  src/planmysem/model/ModelManager.java
  src/planmysem/ui/Gui.java
  test/java/planmysem/logic/Commands/AddCommandTest.java
  test/java/planmysem/logic/Commands/CommandTestUtil.java
  test/java/planmysem/logic/Commands/EditCommandTest.java
Labels: priority.High

#128 Edit FindCommand to generate lastShownList
  src/planmysem/common/Messages.java
  src/planmysem/logic/commands/FindCommand.java
  src/planmysem/logic/parser/ParserManager.java
  src/planmysem/model/semester/WeightedName.java
Labels: priority.High

#131 Add import command
  src/planmysem/logic/commands/ImportCommand.java
  src/planmysem/logic/parser/ParserManager.java
Labels: priority.High

#129 Update view command
  docs/UserGuide.adoc
  src/planmysem/logic/commands/ViewCommand.java
  src/planmysem/logic/parser/ViewCommandParser.java
  src/planmysem/model/semester/Semester.java
  test/java/planmysem/model/PlannerTest.java
Labels: priority.High

#132 Fix storage bug
  docs/DeveloperGuide.adoc
  src/planmysem/Main.java
  src/planmysem/logic/LogicManager.java
  src/planmysem/logic/commands/AddCommand.java
  src/planmysem/logic/commands/DeleteCommand.java
  src/planmysem/logic/commands/EditCommand.java
  src/planmysem/logic/commands/RedoCommand.java
  src/planmysem/logic/commands/UndoCommand.java
  src/planmysem/model/VersionedPlanner.java
  src/planmysem/model/semester/Day.java
  src/planmysem/model/semester/Semester.java
  src/planmysem/storage/Storage.java
  src/planmysem/storage/StorageFile.java
  src/planmysem/storage/jaxb/AdaptedSlot.java
  test/java/planmysem/logic/Commands/AddCommandTest.java
  test/java/planmysem/logic/Commands/DeleteCommandTest.java
  test/java/planmysem/logic/Commands/EditCommandTest.java
  test/java/planmysem/logic/LogicManagerTest.java
Labels: priority.High

#133 Update History Framework & Update Dev Guide
  docs/DeveloperGuide.adoc
Labels: priority.High

#134 Update Dev Guide for view feature
  docs/DeveloperGuide.adoc
  docs/diagrams/ViewMonthSequenceDiagram.pptx
  docs/images/ViewMonthSequenceDiagram.png
Labels: priority.High

#135 Update DeveloperGuide.adoc with Slot management details
  docs/DeveloperGuide.adoc
  src/planmysem/logic/LogicManager.java
  src/planmysem/logic/commands/FindCommand.java
  src/planmysem/model/semester/Day.java
  src/planmysem/model/semester/Semester.java
Labels: priority.High
